name: 01-Building-Blocks
on: [workflow_dispatch]
jobs:
    echo-hello:
        runs-on: ubuntu-latest
        steps:
            - name: echo-hello
              run: echo "Helo, World!"

    echo-goodbye:
        runs-on: ubuntu-latest
        steps:
            - name: Failed step
              run: |
                  echo "i will fail"
                  exit 1
            - name: Goodbye!
              run: echo "Goodbye!"        




