name: 04-workflow
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
        run:
            working-directory: 04-using-actions/react-app 
    steps:
      - name: Checkout Cod
        uses: actions/checkout@v4
      # - name: Printing Folders
      #   run: tree
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Install Dependencies
        # working-directory: 04-using-actions/react-app
        run: npm ci
        # test specified in the package.jason
      - name: Run Unit Tests
        run: npm test 
        
        
