name: 04-workflow
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Cod
              uses: actions/checkout@v4
            - name: Printing Folders
              run: tree   