name: 02-workflow
on: 
    push:
    pull_request:
    schedule:
    - cron: "* * * * *"
    workflow_dispatch:
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: show the trigger
              run: echo "event name is:" ${{ github.event_name }} 