name: event filters & activity types
on: 
    pull_request:
            types: [opened, synchronize]
            branches:
                - main
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: show the trigger
              run: echo "Running whenever a PR is opened & synchronized and base branch is main"                 

    
